/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef _DT_BINDINGS_RESET_QCOM_QCE2204_NSSCC_H
#define _DT_BINDINGS_RESET_QCOM_QCE2204_NSSCC_H

/* QCE2204 NSSCC resets */
#define NSSCC_SWITCH_CORE_BCR			0
#define NSSCC_SWITCH_CORE_ARES			1
#define NSSCC_SWITCH_IPE_ARES			2
#define NSSCC_SWITCH_BTQ_ARES			3
#define NSSCC_SWITCH_MAC0_ARES			4
#define NSSCC_SWITCH_MAC1_ARES			5
#define NSSCC_SWITCH_MAC2_ARES			6
#define NSSCC_SWITCH_MAC3_ARES			7
#define NSSCC_SWITCH_MAC4_ARES			8
#define NSSCC_SWITCH_MAC5_ARES			9
#define NSSCC_MAC0_TX_ARES			10
#define NSSCC_MAC0_TX_SRDS1_ARES		11
#define NSSCC_MAC0_RX_ARES			12
#define NSSCC_MAC0_RX_SRDS1_ARES		13
#define NSSCC_MAC1_TX_ARES			14
#define NSSCC_MAC1_GEPHY0_TX_ARES		15
#define NSSCC_MAC1_SRDS1_CH0_RX_ARES		16
#define NSSCC_MAC1_SRDS1_CH0_XGMII_RX_ARES	17
#define NSSCC_MAC1_RX_ARES			18
#define NSSCC_MAC1_GEPHY0_RX_ARES		19
#define NSSCC_MAC1_SRDS1_CH0_TX_ARES		20
#define NSSCC_MAC1_SRDS1_CH0_XGMII_TX_ARES	21
#define NSSCC_MAC2_TX_ARES			22
#define NSSCC_MAC2_GEPHY1_TX_ARES		23
#define NSSCC_MAC2_SRDS1_CH1_RX_ARES		24
#define NSSCC_MAC2_SRDS1_CH1_XGMII_RX_ARES	25
#define NSSCC_MAC2_RX_ARES			26
#define NSSCC_MAC2_GEPHY1_RX_ARES		27
#define NSSCC_MAC2_SRDS1_CH1_TX_ARES		28
#define NSSCC_MAC2_SRDS1_CH1_XGMII_TX_ARES	29
#define NSSCC_MAC3_TX_ARES			30
#define NSSCC_MAC3_GEPHY2_TX_ARES		31
#define NSSCC_MAC3_SRDS1_CH2_RX_ARES		32
#define NSSCC_MAC3_SRDS1_CH2_XGMII_RX_ARES	33
#define NSSCC_MAC3_RX_ARES			34
#define NSSCC_MAC3_GEPHY2_RX_ARES		35
#define NSSCC_MAC3_SRDS1_CH2_TX_ARES		36
#define NSSCC_MAC3_SRDS1_CH2_XGMII_TX_ARES	37
#define NSSCC_MAC4_TX_ARES			38
#define NSSCC_MAC4_GEPHY3_TX_ARES		39
#define NSSCC_MAC4_SRDS1_CH3_RX_ARES		40
#define NSSCC_MAC4_SRDS1_CH3_XGMII_RX_ARES	41
#define NSSCC_MAC4_RX_ARES			42
#define NSSCC_MAC4_GEPHY3_RX_ARES		43
#define NSSCC_MAC4_SRDS1_CH3_TX_ARES		44
#define NSSCC_MAC4_SRDS1_CH3_XGMII_TX_ARES	45
#define NSSCC_MAC5_TX_ARES			46
#define NSSCC_MAC5_TX_SRDS0_ARES		47
#define NSSCC_MAC5_TX_SRDS0_CH0_XGMII_ARES	48
#define NSSCC_MAC5_RX_ARES			49
#define NSSCC_MAC5_RX_SRDS0_ARES		50
#define NSSCC_MAC5_RX_SRDS0_CH0_XGMII_ARES	51
#define NSSCC_AHB_ARES				52
#define NSSCC_SEC_CTRL_AHB_ARES			53
#define NSSCC_TLMM_ARES				54
#define NSSCC_TLMM_AHB_ARES			55
#define NSSCC_CNOC_AHB_ARES			56
#define NSSCC_MDIO_AHB_ARES			57
#define NSSCC_MDIO_MASTER_AHB_ARES		58
#define NSSCC_TSENS_AHB_ARES			59
#define NSSCC_SRDS0_SYS_ARES			60
#define NSSCC_SRDS1_SYS_ARES			61
#define NSSCC_GEPHY0_SYS_ARES			62
#define NSSCC_GEPHY1_SYS_ARES			63
#define NSSCC_GEPHY2_SYS_ARES			64
#define NSSCC_GEPHY3_SYS_ARES			65
#define NSSCC_SEC_CTRL_ARES			66
#define NSSCC_SEC_CTRL_SENSE_ARES		67
#define NSSCC_SLEEP_ARES			68
#define NSSCC_TS_SLEEP_ARES			69
#define NSSCC_DEBUG_ARES			70

#endif
