/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018,2020 The Linux Foundation. All rights reserved.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DT_BINDINGS_RESET_IPQ_GCC_IPQ9650_H
#define _DT_BINDINGS_RESET_IPQ_GCC_IPQ9650_H

#define GCC_QUPV3_BCR				0
#define GCC_UNIPHY0_BCR				1
#define GCC_UNIPHY1_BCR				2
#define GCC_UNIPHY2_BCR				3
#define GCC_UNIPHY0_SYS_ARES			4
#define GCC_UNIPHY0_AHB_ARES			5
#define GCC_UNIPHY1_SYS_ARES			6
#define GCC_UNIPHY1_AHB_ARES			7
#define GCC_UNIPHY2_SYS_ARES			8
#define GCC_UNIPHY2_AHB_ARES			9
#define GCC_UNIPHY0_XPCS_ARES			10
#define GCC_UNIPHY1_XPCS_ARES			11
#define GCC_UNIPHY2_XPCS_ARES			12
#define GCC_PCIE0_PHY_BCR			13
#define GCC_PCIE0PHY_PHY_BCR			14
#define GCC_PCIE0_PIPE_ARES			15
#define GCC_PCIE0_CORE_STICKY_RESET		16
#define GCC_PCIE0_AXI_M_ARES			17
#define GCC_PCIE0_AXI_S_ARES			18
#define GCC_PCIE0_AXI_M_STICKY_RESET		19
#define GCC_PCIE0_AXI_S_STICKY_RESET		20
#define GCC_PCIE0_AHB_ARES			21
#define GCC_PCIE0_AUX_ARES			22
#define GCC_PCIE1_PHY_BCR			23
#define GCC_PCIE1PHY_PHY_BCR			24
#define GCC_PCIE1_PIPE_ARES			25
#define GCC_PCIE1_CORE_STICKY_RESET		26
#define GCC_PCIE1_AXI_M_ARES			27
#define GCC_PCIE1_AXI_S_ARES			28
#define GCC_PCIE1_AXI_M_STICKY_RESET		29
#define GCC_PCIE1_AXI_S_STICKY_RESET		30
#define GCC_PCIE1_AHB_ARES			31
#define GCC_PCIE1_AUX_ARES			32
#define GCC_PCIE2_PHY_BCR			33
#define GCC_PCIE2PHY_PHY_BCR			34
#define GCC_PCIE2_PIPE_ARES			35
#define GCC_PCIE2_CORE_STICKY_RESET		36
#define GCC_PCIE2_AXI_M_ARES			37
#define GCC_PCIE2_AXI_S_ARES			38
#define GCC_PCIE2_AXI_M_STICKY_RESET		39
#define GCC_PCIE2_AXI_S_STICKY_RESET		40
#define GCC_PCIE2_AHB_ARES			41
#define GCC_PCIE2_AUX_ARES			42
#define GCC_PCIE3_PHY_BCR			43
#define GCC_PCIE3PHY_PHY_BCR			44
#define GCC_PCIE3_PIPE_ARES			45
#define GCC_PCIE3_CORE_STICKY_RESET		46
#define GCC_PCIE3_AXI_M_ARES			47
#define GCC_PCIE3_AXI_S_ARES			48
#define GCC_PCIE3_AXI_M_STICKY_RESET		49
#define GCC_PCIE3_AXI_S_STICKY_RESET		50
#define GCC_PCIE3_AHB_ARES			51
#define GCC_PCIE3_AUX_ARES			52
#define GCC_PCIE4_PHY_BCR			53
#define GCC_PCIE4PHY_PHY_BCR			54
#define GCC_PCIE4_PIPE_ARES			55
#define GCC_PCIE4_CORE_STICKY_RESET		56
#define GCC_PCIE4_AXI_M_ARES			57
#define GCC_PCIE4_AXI_S_ARES			58
#define GCC_PCIE4_AXI_M_STICKY_RESET		59
#define GCC_PCIE4_AXI_S_STICKY_RESET		60
#define GCC_PCIE4_AHB_ARES			61
#define GCC_PCIE4_AUX_ARES			62

#endif
