/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018,2020 The Linux Foundation. All rights reserved.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DT_BINDINGS_CLOCK_IPQ_GCC_IPQ9679_H
#define _DT_BINDINGS_CLOCK_IPQ_GCC_IPQ9679_H

#define GCC_QUPV3_AHB_MST_CLK		0
#define GCC_QUPV3_AHB_SLV_CLK		1
#define GCC_QUPV3_UART0_CLK		2
#define GCC_QUPV3_UART1_CLK		3
#define GCC_SDCC1_AHB_CLK		4
#define GCC_SDCC1_APPS_CLK		5
#define GCC_CMN_12GPLL_AHB_CLK		6
#define GCC_CMN_12GPLL_SYS_CLK		7
#define GCC_UNIPHY0_AHB_CLK		8
#define GCC_UNIPHY1_AHB_CLK		9
#define GCC_UNIPHY2_AHB_CLK		10
#define GCC_UNIPHY0_SYS_CLK		11
#define GCC_UNIPHY1_SYS_CLK		12
#define GCC_UNIPHY2_SYS_CLK		13
#define GCC_NSSNOC_NSSCC_CLK		14
#define GCC_NSSCC_CLK			15
#define GCC_NSSNOC_SNOC_CLK		16
#define GCC_NSSNOC_SNOC_1_CLK		17
#define GCC_PCIE0_AHB_CLK		18
#define GCC_ANOC_PCIE0_1LANE_M_CLK	19
#define GCC_ANOC_PCIE0_1LANE_S_CLK	20
#define GCC_PCIE0_AXI_M_CLK		21
#define GCC_PCIE0_AXI_S_CLK		22
#define GCC_PCIE0_AUX_CLK		23
#define GCC_PCIE0_AXI_S_BRIDGE_CLK	24
#define GCC_PCIE0_RCHNG_CLK		25
#define GCC_PCIE0_PIPE_CLK		26
#define GCC_PCIE1_AHB_CLK		27
#define GCC_ANOC_PCIE1_2LANE_M_CLK	28
#define GCC_ANOC_PCIE1_2LANE_S_CLK	29
#define GCC_PCIE1_AXI_M_CLK		30
#define GCC_PCIE1_AXI_S_CLK		31
#define GCC_PCIE1_AUX_CLK		32
#define GCC_PCIE1_AXI_S_BRIDGE_CLK	33
#define GCC_PCIE1_RCHNG_CLK		34
#define GCC_PCIE1_PIPE_CLK		35
#define GCC_PCIE2_AHB_CLK		36
#define GCC_ANOC_PCIE2_2LANE_M_CLK	37
#define GCC_ANOC_PCIE2_2LANE_S_CLK	38
#define GCC_PCIE2_AXI_M_CLK		39
#define GCC_PCIE2_AXI_S_CLK		40
#define GCC_PCIE2_AUX_CLK		41
#define GCC_PCIE2_AXI_S_BRIDGE_CLK	42
#define GCC_PCIE2_RCHNG_CLK		43
#define GCC_PCIE2_PIPE_CLK		44
#define GCC_PCIE3_AHB_CLK		45
#define GCC_ANOC_PCIE3_2LANE_M_CLK	46
#define GCC_ANOC_PCIE3_2LANE_S_CLK	47
#define GCC_PCIE3_AXI_M_CLK		48
#define GCC_PCIE3_AXI_S_CLK		49
#define GCC_PCIE3_AUX_CLK		50
#define GCC_PCIE3_AXI_S_BRIDGE_CLK	51
#define GCC_PCIE3_RCHNG_CLK		52
#define GCC_PCIE3_PIPE_CLK		53
#define GCC_PCIE4_AHB_CLK		54
#define GCC_ANOC_PCIE4_1LANE_M_CLK	55
#define GCC_ANOC_PCIE4_1LANE_S_CLK	56
#define GCC_PCIE4_AXI_M_CLK		57
#define GCC_PCIE4_AXI_S_CLK		58
#define GCC_PCIE4_AUX_CLK		59
#define GCC_PCIE4_AXI_S_BRIDGE_CLK	60
#define GCC_PCIE4_RCHNG_CLK		61
#define GCC_PCIE4_PIPE_CLK		62
#define GCC_QDSS_DAP_CLK		63
#define GCC_QDSS_AT_CLK			64
#define GCC_QUPV3_SPI0_CLK		65
#define GCC_QPIC_AHB_CLK		66
#define GCC_QPIC_CLK			67
#define GCC_QPIC_IO_MACRO_CLK		68
#define GCC_QUPV3_I2C0_CLK		69
#define GCC_QUPV3_I2C1_CLK		70
#define GCC_PRIME_CORE_CLK		71

#endif
